### ISSUE TITLE
Unable to get comments data

### ISSUE THREAD

**Issue by team-wealthian** [VirtusLab-Open-Source/strapi-plugin-comments#99]
### I trying to integrate this module into my stapi project as per your documentation but i am getting **{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}**  error when ever I am trying make rest api get call  for **http://localhost:1337/comments/api::post.post:1**

When I tried to  navigate in comments section of admin portal, I can see my console as,

![image](https://user-images.githubusercontent.com/95869391/151550213-655b4dec-09e8-47f5-8b3c-bc7cba429118.png)

with my admin panel as,

![image](https://user-images.githubusercontent.com/95869391/151550420-3e1fefaf-a113-4d6f-b335-654e9d170443.png)

content of my package.json file is,

{
  "name": "app-name",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.48.0",
    "@strapi/plugin-i18n": "4.0.0",
    "@strapi/plugin-users-permissions": "4.0.0",
    "@strapi/provider-email-nodemailer": "^4.0.3",
    "@strapi/provider-email-sendgrid": "^4.0.3",
    "@strapi/provider-email-sendmail": "^4.0.0",
    "@strapi/strapi": "4.0.0",
    "@strapi/utils": "^4.0.0",
    "aws-sdk": "^2.892.0",
    "axios": "^0.24.0",
    "bad-words": "^3.0.4",
    "lodash": "^4.17.21",
    "nodemailer": "^6.7.2",
    "pg": "^8.7.1",
    "sendmail": "^1.6.1",
    "sqlite3": "5.0.2",
    "strapi-plugin-comments": "^2.0.0-beta.3",
    "strapi-provider-upload-aws-s3": "^3.6.8",
    "strapi-provider-upload-aws-s3-advanced": "^4.0.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "unique id"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

installed node version is  15.14.0
npm version is  7.7.6

I have enabled all the setting for comments plugin for making a rest api call from setting tab> role for all users .

Content of my plugin.js is,

comments: {
    enabled: true,
    config: {
      enableUsers: false,
    },
    badWords: false,
    moderatorRoles: ["Public"],
    approvalFlow: ["api::post.post"],
    entryLabel: {
      "*": ["Title", "title", "Name", "name", "Subject", "subject","id"],
      "api::post.post": ["id"],
    },
    reportReasons: {
      MY_CUSTOM_REASON: "MY_CUSTOM_REASON",
    },
  }

**Can you please help me to fix this issue**

**Comment by team-wealthian** [comment]
@cyp3rius 
We have upgraded with version rc.1.
In we have configured our entity on api::post.post we can access the same using **http://localhost:1337/api/posts**

Now we have tried to make a post a call for 

**http://localhost:1337/comments/api::post.post:1**

with request body as 
**{
    "author": {
        "id": "11",
        "name": "Joe Doe",
        "email": "jdoe@sample.com",
        "avatar": "sample url"
    },
	"content": "My sample response"
}**

in the postman i am getting an error,

    **{"data":null,"error":{"status":400,"name":"Error","message":"invalid JSON, only supports object and array"}}**

and in in the console I am getting error as,

![image](https://user-images.githubusercontent.com/95869391/151656362-62da6bf1-201e-42c8-8a34-56cd4e33dd4a.png)


Please help

**Comment by cyp3rius** [comment]
Ok, so seems something with payload, how you are making the call? Which lib is used? Have you tried postman / any API test suite?

I would like to eliminate the data transform issues between API and client first.

Regards,
Matt

**Comment by team-wealthian** [comment]
we are using postman. There is one thing that I have noted ...with graphql it is working pretty smoothly.  Not sure why it is failing with rest api

**Comment by cyp3rius** [comment]
I've recognized what was wrong. Endpoints mentioned in the `Readme.md` were missing the `api/` part so you've to use `http://localhost:1337/api/comments/api::post.post:1` instead of `http://localhost:1337/comments/api::post.post:1`.

Documentation has been already fixed.

**Comment by M1ck0** [comment]
@cyp3rius Docs are still not fixed, as you can see in the image.

![image](https://user-images.githubusercontent.com/19279947/155888532-863ff399-2031-4a49-bb6a-5e5b96a12cde.png)

**Comment by cyp3rius** [comment]
Will pick it up on Monday with some first commits
